### ISSUE TITLE
Define test approach for a resource oriented architecture and identify testing tools and techniques

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs30#1]

**Comment by dstenger** [comment]
As test suite will be written in TestNG, any Java HTTP client (for request) and any parser (for response) can be used for testing.

Following libraries/frameworks can be used to make the creation of tests easier and readability better:

* Jersey
* Spring RestTemplate
* [REST-assured](https://github.com/rest-assured/rest-assured)
* ...

**Comment by cmheazel** [comment]
I have been working with KaiZen as an OpenAPI parser.  I have used it to hacked together a driver which will crawl through an OpenAPI document reporting the contents and generating absolute paths.

**Comment by dstenger** [comment]
@cmheazel Can you provide any code and/or more detailed informations (e.g. web site) about this parser?

**Comment by cmheazel** [comment]
@dstenger KaiZen is at https://github.com/RepreZen/KaiZen-OpenAPI-Parser.  It parses and OpenAPI doc (both JSON and YAML) and generates a corresponding set of Java objects.  You can then start with the "model" object and traverse the OpenAPI content.  I'll post the crawler on my GitHub page once I get a chance to clean it up a bit.

**Comment by lgoltz** [comment]
First trials with 
 * rest-asured: https://github.com/opengeospatial/ets-wfs30/tree/rest-assured-1
  * Using the rest-assured API leads to the problem that the log request/response (in case of a failure) must be logged via a Filter (in CommonFixture). A PrintStream is used currently, the output can be verified in the test landingPageRetrievalFail.
 * KaiZen: https://github.com/opengeospatial/ets-wfs30/tree/rest-assured-kayzen-1 
  * Test was changed to request f=json.

**Comment by dstenger** [comment]
**rest-assured**

Readability of tests is good.
I don't see a problem using the filter mechanism of rest-assured instead of instance of ```ITestResult```.

**KaiZen**

Parser makes parsing of OpenAPI 3.0 documents easier.
I do not see any drawbacks.

**Comment by dstenger** [comment]
Decision:
**rest-assured** and **KaiZen-OpenAPI-Parser** are used to develop tests.
