### ISSUE TITLE
Prepare ETS

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wfs30#10]

**Comment by dstenger** [comment]
Commits:
* https://github.com/opengeospatial/ets-wfs30/commit/211bbc375b03ab138eef578a4dd4d97309f89c81
* https://github.com/opengeospatial/ets-wfs30/commit/e7804ce588c642ca3ae1d716286e6d21e47bea5c
* https://github.com/opengeospatial/ets-wfs30/commit/4481b82624050f82b8a6aea5a97d7145ca83e463
