### ISSUE TITLE
Introduce Dockerfile and Maven Docker plugin

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs30#13]

**Comment by dstenger** [comment]
Commit (master Branch): https://github.com/opengeospatial/ets-wfs30/commit/dcd4dbdb2dc5fed957404c24a9d8914bc6009f51

**Comment by dstenger** [comment]
**Useful commands:**

Build Docker Image:
* mvn clean install -Pdocker
* -> Docker Image with Name ```opengeospatial/ets-wfs30``` is created.

Build Docker Image and create and start Docker container:
* mvn clean install docker:run -Pdocker
* -> Test suite can be accessed via http://localhost:8081/teamengine

**Comment by lgoltz** [comment]
Added configuration of the te_base directory as volume (default of the  property `docker.tebase.dir`  is the target directory):

Build Docker Image and create and start Docker container with volume `~/teamengine/users`:
```
mvn clean install docker:run -Pdocker -Ddocker.tebase.dir=~/teamengine/users
```

**Comment by dstenger** [comment]
Wiki page was created: https://github.com/opengeospatial/cite/wiki/How-to-add-creation-of-Docker-Image-to-test-suites
