### ISSUE TITLE
Create skeleton of TestNG based test suite

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs30#2]

**Comment by dstenger** [comment]
= Further adjustments

Add gitignore: https://github.com/opengeospatial/ets-wfs30/commit/6a06f66d91fe41ec9e27645d41a611365e55a752
Update spec-version and ets-common version: https://github.com/opengeospatial/ets-wfs30/commit/8380e3a1e639dc58897f16400918ee5a42283666
Remove method assertSchematronValid: https://github.com/opengeospatial/ets-wfs30/commit/5b0fdae658ec1d6da6899b16af5394b692ea1d24

**Comment by lgoltz** [comment]
Skeleton of the test suite was created. `mvn clean install` was successful.
