### ISSUE TITLE
Create release 0.1

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs30#26]

**Comment by dstenger** [comment]
#### Prepare release (for each test suite individually)

- [ ]  The master branch should contain the latest "stable" version. Make sure all verified pull requests are merged.
- [ ]  Make sure it builds properly running `mvn clean install site`.
- [ ] Test locally the master branch with the [reference implementation](https://github.com/opengeospatial/cite/wiki/Reference-Implementations), if there is one.
	- If it is OK, continue, if not create or update an issue, in the issue tracker of that test.
- [ ] Review closed issues to be included in the release. 
	- Update title if appropriate.
	- Tag, if they are not tagged with the milestone number.
- [ ] Update release notes, usually the file is at src/site/markdown/relnotes.md.
	- Add a new title for the revision, if there is not one already.
	- Copy the issues to be included in the release, link and title.
	- Add any other highlights.
- [ ] Create a new issue in the [OGC release tracker](https://github.com/opengeospatial/te-releases/issues) and set label `approved-by-test-lead`.
	- Write a title for the issue should containing: [Abbreviation] [version] revision [revision] in *Beta*. For example: WFS 1.1 revision 1.23 in Beta. It should always be in Beta. OGC staff will create the issue related to making the releases in the production, official web site.

**Comment by dstenger** [comment]
#### Create release (for each test suite individually)

- [ ] In the [OGC release tracker](https://github.com/opengeospatial/te-releases/issues) assign the issue to a milestone.
- [ ] Check that the issues and pull requests in the ETS issue tracker are properly written and associated to the correct milestone. Make sure issues are closed in the ETS issue tracker.
- Do the release. Process involves creating a revision based on the pom.xml version, updating the GitHub page, tag, and updating the revision on the pom for the next release. 
   - [ ] Check if Maven configuration has been updated: [How to create Releases with Maven](https://github.com/opengeospatial/cite/wiki/How-to-create-Releases-with-Maven).
   - [ ] Create release with [Jenkins](http://build.opengeospatial.org/jenkins/).
- [ ] Close milestone in the ETS issue tracker.
- [ ] Publish releases on Central Maven Repository: [Close the staging repository](https://github.com/opengeospatial/cite-private/wiki/How-to-deploy-on-Central-Maven-Repository#close-the-staging-repository) and [Release](https://github.com/opengeospatial/cite-private/wiki/How-to-deploy-on-Central-Maven-Repository#release).

**Comment by dstenger** [comment]
Information was published via mailing list.

----

All,

I am happy to announce that version 0.1 of test suite for WFS 3.0 was
released.

The release covers an implementation of Core conformance class.

Release includes following:
* Tag is created on GitHub [1].
 * Build of tag can easily be executed with Docker [2].
* Artifacts are uploaded to Central Maven Repository [3].
* Release notes are published [4].

Currently, the release is not installed on beta environment of OGC.

Happy testing!

Regards,
Dirk

[1] https://github.com/opengeospatial/ets-wfs30/tree/0.1
[2]
https://github.com/opengeospatial/cite/wiki/How-to-add-creation-of-Docker-Image-to-test-suites
[3] https://search.maven.org/#search|ga|1|a%3A%22ets-wfs30%22
(Publishing to search engine is still pending and it might take a couple
of hours till the artifacts are available)
[4] https://opengeospatial.github.io/ets-wfs30/changelog.html

**Comment by lgoltz** [comment]
[Release 0.1](https://github.com/opengeospatial/ets-wfs30/releases/tag/0.1) was created and is available on central maven repository.
