### ISSUE TITLE
Providing landing page as "iut" results in a NullPointerException

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ets-wfs30#27]
The README.md does not say which URL to provide (exemplifies a xml schema location instead), but giving a landing page one results in a NPE here:
https://github.com/opengeospatial/ets-wfs30/blob/a25a516309a54384599db5d0346ddb6b7c1e189a/src/main/java/org/opengis/cite/wfs30/collections/FeatureCollectionsMetadataOperation.java#L84

The method is apparently using the user provided URI to make the request, getting a landing page, that has no "collections" element, but just links to API, conformance and the collections page.

Giving the test a collections page link makes this pass. As discussed in the meeting, there is confusing about which URL one would have to give the tests, so maybe the easiest approach for the users is to accept any of them and adapt as a consequence (each has unique attributes that should help identify what one has got).

**Comment by aaime** [comment]
Giving the tests the "collections" page makes that test pass, but it seems the same URI is also used in the LandingPage class, which results in a odd error message:

"The landing page must include at least links with relation type 'service', 'conformance' and 'data', but contains [self, alternate] expected [true] but found [false]"

The "Expected true but found false is a side effect of the assertTrue call, but don't think the user should see it (seems to imply a "true" or "false" rel are needed).

**Comment by aaime** [comment]
Ah, in case you want to reproduce, use this as the "iut": http://cloudsdi.geo-solutions.it/geoserver/wfs3
The server there still deploys three times a day and does not have all the latest fixes, but has enough to reproduce the NPE issue.

**Comment by aaime** [comment]
Hum... how are you getting to the collections page? I've tried to just look at the code, and it seems to be using the rootURI, without adding "/collections", however, the actual request seems impossible to debug, rest assured is written in groovy and intelllij cannot give anything meaningul when decompiling its sources while I try to "step in" into the "request" method.

**Comment by lgoltz** [comment]
Thanks a lot for your feedback! As far as I see we have several issues here:
1. Enhance the documentation (see #9). 
1. Improve the ETS to accept the URL to the landing page or the API definition. Currently the URL to the landing page must be provided. 
1. The collections are currently parsed from the landing page to test [A.4.4.5. Validate the Feature Collections Metadata Operation Response](https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html#_validate_the_feature_collections_metadata_operation_response) (Test method 4. Validate that the returned document includes a collections property for each collection in the dataset.). Meanwhile I think this test method cannot be tested by ETS as there is no list of collections provided by the WFS. The collections must be named in the landing page and a templateing mechanism can be used in the APE definition (https://github.com/opengeospatial/WFS_FES/blob/master/openapi.yaml)  @aaime What do you think? 
The affected test is FeatureCollectionsMetadataOperation.validateFeatureCollectionsMetadataOperationResponse_Collections (). 
1. Improve message of failing test LandingTest.landingPageValidation()
1. The collections page is retrieved using a parsed TestPoint for 'collection' from the API definition. We have strictly implemented [A.4.3.2. Identify Server URIs](https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html#_identify_server_uris) to identify the test points (see also #24).

**Comment by aaime** [comment]
I think there is a misunderstanding of the spec here (or between us). The landing page does not contain the list of collections, it merely has a links to the collection metadata operation. The links must be followed and the collection metadata operation used to run test A.4.4.5

By specification, even the OpenAPI must contain a "collections" endpoint, not a "collection" one. Following it gives you a full list of collections, e.g:
* http://cloudsdi.geo-solutions.it/geoserver/daraa/wfs3/api?f=application%2Fopenapi%2Bjson%3Bversion%3D3.0
* http://cloudsdi.geo-solutions.it/geoserver/wfs3/collections/?f=application%2Fjson

**Comment by lgoltz** [comment]
Yes, I agree with you. That's why I think the test method `4. Validate that the returned document includes a collections property for each collection in the dataset.` is not testable by the ETS as we know the "collections" only from the feature collection metadata operation response which is the returned document under test.

**Comment by aaime** [comment]
Works for me
