### ISSUE TITLE
Enhance ETS to run against server implementing the compact API flavor

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ets-wfs30#28]
GeoServer does not implement a "collection by collection" API declaration, but opts for the more compact approach of having collection names as parameters and a single collections/items endpoint, as also exemplified on the WFS3 repository:

https://github.com/opengeospatial/WFS_FES/blob/master/openapi.yaml

However the test tries to find an explicit API endpoint for a given collection, and not finding it, skips the GetFeature tests:
* https://github.com/opengeospatial/ets-wfs30/blob/2759bc67ec86faf1c09c55c47f6d9cb1c797ee59/src/main/java/org/opengis/cite/wfs30/collections/GetFeaturesOperation.java#L220

The compact approach has been chosen as servers with tens of thousands of collections, or more, (not uncommon unfortunately) would end up getting a API document that's too large for clients to handle.
I believe that Interactive Instrument chose the explicit paths, while Cubewerx has it configurable.

**Comment by lgoltz** [comment]
Thank you for reporting. 
You are right, this approach is currently not handled by the ETS.

**Comment by dstenger** [comment]
@aaime Can you please rerun the test suite (master branch)? Now, all collections should be recognized.
