### ISSUE TITLE
Test validateCollectionsMetadataDocument_Links fails  

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wfs30#36]
The test FeatureCollectionsMetadataOperation.validateCollectionsMetadataDocument_Links() currently fails against http://cloudsdi.geo-solutions.it/geoserver/wfs3 multiple times with the failure `Collections Metadata document must include links with relation 'item' for each supported encodings. Missing links for types [text/xml application/x-yaml]  `

The tests checks for each collection in the [collections metadata response](http://cloudsdi.geo-solutions.it/geoserver/wfs3/collections?f=application%2Fjson) if there are links for alternative encodings in every other media type described in the [API definition](http://cloudsdi.geo-solutions.it/geoserver/wfs3/api?f=application%2Fjson).

Expected are "Alternate encodings of this document in every other media type as identified by the compliance classes for this server.", as described in https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html#_validate_the_feature_collections_metadata_operation_response 

**Known conformance classes and expected media types:**
* http://www.opengis.net/spec/wfs-1/3.0/req/html
   * `text/html`
   * https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html#_requirement_class_html
* http://www.opengis.net/spec/wfs-1/3.0/req/geojson
   * `application/geo+json` for feature collections and features
   * `application/json` for all other resources.
   * https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html#_requirement_class_geojson
 * http://www.opengis.net/spec/wfs-1/3.0/req/gmlsf0
   * `application/gml+xml; version=3.2;profile=http://www.opengis.net/def/profile/ogc/2.0/gml-sf0` for feature collections and features
   * `application/xml` for all other resources
   * https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html#_requirement_class_geography_markup_language_gml_simple_features_profile_level_0
* http://www.opengis.net/spec/wfs-1/3.0/req/gmlsf2
  * `application/gml+xml; version=3.2;profile=http://www.opengis.net/def/profile/ogc/2.0/gml-sf2` for feature collections and features
  * `application/xml` for all other resources
  * https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html#_requirement_class_geography_markup_language_gml_simple_features_profile_level_2

**Comment by lgoltz** [comment]
The same applies to the test FeatureCollectionsMetadataOperation.validateFeatureCollectionsMetadataOperationResponse_Links() (which does not fail, but the test method is the same).

**Comment by lgoltz** [comment]
As already documented in https://github.com/opengeospatial/ets-wfs30/issues/7#issuecomment-400308380 the second test method of A.4.4.6. Validate a Collections Metadata document does not match the Requirement 13: 

Test method:
```
2. Validate that the collection metadata document includes links for:
  * Itself
  * Alternate encodings of this document in every other media type as identified by the 
     compliance classes for this server.
```


Requirement 13:
```
/req/core/fc-md-items-links

For each feature collection in this distribution of the dataset, the links property of the 
collection SHALL include an item for each supported encoding with a link to the 
collection resource (relation: item).

All links SHALL include the rel and type properties.
```

Expected test method:
```
2. Validate that the collection metadata document includes links to the collection for each 
    supported media type as identified by the compliance classes for this server.
```

**Comment by lgoltz** [comment]
Fixed with #37. Following tests still fails:

**WFS: http://cloudsdi.geo-solutions.it/geoserver/wfs3/**
* validateFeatureCollectionsMetadataOperationResponse_Links with failure: "Feature Collection Metadata document must include links for alternate encodings. Missing links for types [application/xml]"
   * `text/xml` is supported, but GML SF0 and SF2 expects `application/xml`
* validateCollectionsMetadataDocument_Links (several times) with failure: "Collections Metadata document for collection with name eumetsat__ne_10m_coastline must include links with relation 'item' for each supported encodings. Missing links for types application/gml+xml;version=3.2;profile=http://www.opengis.net/def/profile/ogc/2.0/gml-sf0"
  * `application/gml+xml; version=3.2` is supported, but GML SF0 expects `application/gml+xml; version=3.2; profile=http://www.opengis.net/def/profile/ogc/2.0/gml-sf0`

**WFS:  https://www.ldproxy.nrw.de/rest/services/kataster/** 
* validateFeatureCollectionsMetadataOperationResponse_Links with failure: "Feature Collection Metadata document must include links for alternate encodings. Missing links for types [application/xml] "
   * `text/xml` is supported, but GML SF0 and SF2 expects `application/xml`

**Comment by aaime** [comment]
Test is still failing, but in a different way.
I'm now getting a:
``Collections Metadata document must include links with relation 'item' for each supported encodings. Missing links for types [text/xml, application/x-yaml] expected [true] but found [false]>``

However, the API document does not declare "text/xml" nor "application/x-yaml" for the items endpoints, but only for the collection one. One is data, the other is description, they are different documents with different encodings. Debugging the code, the test is picking the media types to be supported from "/collections", so somewhat assuming whatever format can be used to encode a collection description, but it's not the case, see:
https://github.com/opengeospatial/ets-wfs30/blob/c44cb06663cb2895599d740b2792392d1d9e0ec3/src/main/java/org/opengis/cite/wfs30/collections/FeatureCollectionsMetadataOperation.java#L221

**Comment by lgoltz** [comment]
@aaime I assume you've tested with the current master?  The failure should be fixed with PR #37, which is not merged yet.

**Comment by aaime** [comment]
I did test the master, yes.. thought everything was ready and merged already, I have missed the PRs were yet to be integrated

**Comment by dstenger** [comment]
@aaime 

PR is merged now.

However, as described in https://github.com/opengeospatial/ets-wfs30/issues/36#issuecomment-413116902, the test is still failing with http://cloudsdi.geo-solutions.it/geoserver/wfs3/.

In our opinion, the test failure is correct.
If you disagree, please open a new issue or we can discuss this during the weekly meeting.
