### ISSUE TITLE
Implement A.4.2. Retrieve the API Description

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wfs30#4]
Includes
* [x] A.4.2.1. Landing Page Retrieval
* [x] A.4.2.2. Landing Page Validation
* [x] A.4.2.3. OpenAPI Document Retrieval
* [x] A.4.2.4. API Definition Validation

**Comment by lgoltz** [comment]
Tests was implemented (Further steps of test A.4.2.4. API Definition Validation will be implemented in #5).
PR: #11

**Comment by dstenger** [comment]
Few improvements to be more close to ATS: https://github.com/opengeospatial/ets-wfs30/commit/cd496f6537421bd769350cb45dfd67b966cf3043

**Comment by dstenger** [comment]
Add dependency to test ```apiDefinitionValidation```: https://github.com/opengeospatial/ets-wfs30/commit/03fe489af564af812ca01b377c8ce145dd1fd59a

**Comment by dstenger** [comment]
For integration tests Maven plugin ```maven-failsafe-plugin``` was configured in profile ```web-dependencies```.

Commit: https://github.com/opengeospatial/ets-wfs30/commit/ecd7c74ac0d59cb1bcff78089421b9e74a996e55

Integration tests can be run with: ```mvn clean verify -Pweb-dependencies```

**Comment by dstenger** [comment]
Updated tests regarding Accept HTTP header: https://github.com/opengeospatial/ets-wfs30/commit/8d6686a9d7de28d63a779a8f1e78119ee0e3769c
