### ISSUE TITLE
Bounding box tests over polar area use invalid latitude values

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ets-wfs30#42]
The current tests use latitude values up to 160° for the polar regions test:

https://github.com/opengeospatial/ets-wfs30/blob/5f32b86405484efeeb38ede0b875465edb57f897/src/main/java/org/opengis/cite/wfs30/collections/GetFeaturesOperation.java#L118

However 160 is an invalid latitute, checking the specification I see no allowance to use such a high value.
In GeoServer the WFS engine is shared among the various versions, and for older specs a test for valid values was requested, said testing is now complaining, a request like:

http://localhost:8081/geoserver/wfs3/collections/sf__AggregateGeoFeature/items?bbox=-70.0000000%2C-20.0000000%2C-70.0000000%2C160

results in:

```
{
code: "InvalidParameterValue",
description: "bounding box out of valid range of crs"
}
```

The ATS only asks to test polar area, does not require to use invalid latitude value. I'd suggest to limit the maximum latitude to 90, and maybe test both poles.

**Comment by aaime** [comment]
Hi, has there been any progress on this ticket?

**Comment by aaime** [comment]
Opened a related ticket on the specification, to see if the issue should be handled there, instead of here:
https://github.com/opengeospatial/WFS_FES/issues/163

**Comment by lgoltz** [comment]
@aaime Thank you for reporting!

> Opened a related ticket on the specification, to see if the issue should be handled there, instead of here:
opengeospatial/WFS_FES#163

I think the test should use correct bounding boxes. Currently test for exceptions are not described in the ATS. 
The polar regions tests should use the following bounding boxes (e.g):
  * -180.0, 85.0, 180.0, 90.0 
  * -180.0, -85.0, 180.0, -90.0 

@aaime Do you agree?

**Comment by aaime** [comment]
Those bounding boxes work fine for me. Would still be interesting to know if the spec leaders want to give the spec a "rigid" or "forgiving" approach when it comes to invalid coordinate values.

**Comment by lgoltz** [comment]
Fixed with https://github.com/opengeospatial/ets-wfs30/commit/4c108378ed54eeca215932615071edbcb6e53910 on master.

**Comment by aaime** [comment]
Yep, that fixed it, thank you!
