### ISSUE TITLE
Manage getFeatureUrlWithFeatureId when no query string

### ISSUE THREAD

**Issue by ThomasG77** [opengeospatial/ets-wfs30#54]
I'm implementing an Express based server WFS 3.0 (not public, need to be hardened before publication), I do not provide at the moment an output format like "?f=json" as I use only default output to json.
In the code of test for `getFeatureOperation` https://github.com/opengeospatial/ets-wfs30/blob/master/src/main/java/org/opengis/cite/wfs30/collections/GetFeatureOperation.java#L102 the test presumes that there is always a query string with `getFeatureUrl.indexOf( "?" )`
When none is present, the value for `getFeatureUrl.indexOf( "?" )` is `-1`, `getFeatureUrl.substring( 0, getFeatureUrl.indexOf( "?" ) )` returns an exception `java.lang.StringIndexOutOfBoundsException: String index out of range: -1` and I got failed tests.

To solve the issue, I've changed code to the following:

```java
String getFeatureUrlWithFeatureId;
if (getFeatureUrl.indexOf( "?" ) == -1) {
    getFeatureUrlWithFeatureId = getFeatureUrl + "/" + featureId;
} else {
    getFeatureUrlWithFeatureId = getFeatureUrl.substring( 0, getFeatureUrl.indexOf( "?" ) ) + "/" + featureId;
}
```

Thanks for your feedback. If my issue is relevant, I can make a PR. Feel free to also comment the alternate code itself. I don't often code with Java so the code can be clumsy.

**Comment by dstenger** [comment]
Thank you for this bug report and the provided fix.
Yes, please create a pull request. We very much appreciate that.
