### ISSUE TITLE
how to address skipped tests

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ets-wfs30#58]
Using the ets-wfs30 Docker image, our testing of [pygeoapi](https://pygeoapi.io) results in:

Pass: 21 | Fail: 0 | Skip: 3 | Total tests: 24

The 3 skipped tests are show below.  Not sure if this is a bug in the tests or how the these should be interpreted.

bounding Box Parameter | Implements A.4.4.12. Bounding Box Parameter (Requirement 20) \|                    Details ↗ | 02:34:05 | 0 ms | java.lang.IndexOutOfBoundsException: toIndex = 3
-- | -- | -- | -- | --
 
 
limit Parameter | Implements A.4.4.11. Limit Parameter (Requirement 18) \|                    Details ↗ | 02:34:05 | 0 ms | java.lang.IndexOutOfBoundsException: toIndex = 3
 
 
time Parameter | Implements A.4.4.13. Time Parameter (Requirement 22) \|                    Details ↗ | 02:34:05 | 0 ms | java.lang.IndexOutOfBoundsException: toIndex = 3

**Comment by lgoltz** [comment]
@tomkralidis Thanks for reporting this. Seems to be a bug. Can you provide the service URL or at least the OpenAPI document describing the service?

**Comment by tomkralidis** [comment]
@lgoltz sample URL at http://geo.kralidis.ca/pygeoapi/

**Comment by lgoltz** [comment]
@tomkralidis The fix will provided in version 0.4. Until the new release is available you could select "All collections" instead of the "Limited number of collections: 3" after the new session was started.

**Comment by dstenger** [comment]
Fix was successfully tested and merged into master branch.

@tomkralidis You can easily build a Docker Image and start a Docker Container of master branch by executing `mvn clean install docker:run -Pdocker`.

**Comment by tomkralidis** [comment]
@dstenger is the docker image updated?  Currently I'm just pulling the built image from Docker Hub.

**Comment by dstenger** [comment]
No, unfortunately, Image on Docker Hub will be updated when we create the next release (this or next month).
However, you can either install Maven and execute above mentioned command in cloned repository or you can also try the workaround proposed by lgoltz.
