### ISSUE TITLE
A.4.4.14 skipped test - 'No featureId available'

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ets-wfs30#62]
Hi: I am getting a skipped test per below. Can someone provide a suggestion on what the tests are looking for so as NOT to skip?

get Feature Operation | Implements A.4.4.14. Get Feature Operation (Requirement 30, 31) \|                    Details ↗ | 03:39:48 | 0 ms | No featureId available for collection 'ne_110m_populated_places_simple'
-- | -- | -- | -- | --

**Comment by lgoltz** [comment]
@tomkralidis Can you provide the url of the service?

This featureId may be empty if the collection with the name ne_110m_populated_places_simple is empty or the id is missing.

**Comment by tomkralidis** [comment]
@lgoltz http://ec2-18-222-159-167.us-east-2.compute.amazonaws.com/pygeoapi/ (for testing)

**Comment by dstenger** [comment]
@tomkralidis Can you provide the test service again? I can take a look at it, now (at Hackathon).

**Comment by tomkralidis** [comment]
http://ec2-18-222-159-167.us-east-2.compute.amazonaws.com/ (at Hackathon too, at the Processing table come by!)

**Comment by dstenger** [comment]
There is a bug in the test suite.
`org.opengis.cite.wfs30.util.JsonUtils#parseFeatureId` didn't accept feature ids of type integer. As your service just contains integer feature ids, none of the ids was processed.

I created a pull request to fix this issue. A functional test with your service was successful.

**Comment by tomkralidis** [comment]
Testing against a locally built docker image (with #71 as a hotfix) fixes the issue.  Thanks!
