### ISSUE TITLE
A.4.4.10 number of features evaluation

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ets-wfs30#64]
Hi: I am getting a skipped test per below.  My collection has 242 features.  Where is the value 2818 coming from?

validate The Get Features Operation Response_property_number Matched | Implements A.4.4.10. Validate the Get Features Operation Response (Requirement 28) \|                    Details ↗ | 03:39:44 | 3s | Value of numberReturned (242) does not match the number of features in all responses (2818)
-- | -- | -- | -- | --

**Comment by lgoltz** [comment]
The test iterates over all `next` links in the response beginning with the first one and counts all features in the responses. 
@tomkralidis Can you provide the URL of the service?

**Comment by tomkralidis** [comment]
@lgoltz http://ec2-18-222-159-167.us-east-2.compute.amazonaws.com/pygeoapi/

**Comment by lgoltz** [comment]
@tomkralidis  The test uses the parameter `limit` with the maximum value describe in the OpenAPI document. 10000 described in http://ec2-18-222-159-167.us-east-2.compute.amazonaws.com/pygeoapi/api?f=json

The request http://ec2-18-222-159-167.us-east-2.compute.amazonaws.com/pygeoapi/collections/ne_110m_populated_places_simple/items?f=json&limit=10000 returns 242 features (as expected cause `numberMatched=242` and `numberReturned=242`), but the `next` link contains `startindex=10`  (http://ec2-18-222-159-16…ple/items/?startindex=10). From my point of view this should be `startindex=10000`. So I assume this is a issue of the service. 
But we should try to improve the exception handling: 
 * At least the link(s) should be added to the report. 
 * Improve the documentation. 
 * Shall we add a new test to test the correct value of the limit/startindex? Maybe the ATS should be improved also.

**Comment by tomkralidis** [comment]
Thanks @lgoltz fixed on our side.  CITE test now does not skip.  Thanks.
