### ISSUE TITLE
Create documentation of test suite

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs30#9]
This includes:
* [x] **site documentation** (all documentation displayed via ```[TEAMENGINE_ENDPOINT]/about/[TEST_SUITE_ID]/[SPEC_VERSION]/site/``` is up to date)
* [x] **REST API documentation** (all documentation displayed via REST API (e.g. ```[TEAMENGINE_ENDPOINT]/rest/suites/```) is up to date)
* [x] **Web Browser Interface documentation** (all displayed content in Web Browser Interface is up to date)
* [x] **Test result**: Applies to new HTML report and old report. If a test fails, a link to Java Doc is provided. This URL is currently not correct.

Hints:
* site documentation describes exactly how the tests can be mapped to specification (e.g. abstract test suite described in specification is implemented).
  * This includes a description of the structure of the test suite.
* site documentation references all relevant documents (e.g. specification).
* site documentation lists all preconditions and restrictions of test suite.

**Comment by dstenger** [comment]
Describe what URLs can be tested.

**Comment by lgoltz** [comment]
> REST API documentation

Commit: https://github.com/opengeospatial/ets-wfs30/commit/6c2a00af1b94dcce274fd0cf1bc4d75c090c49df

**Comment by lgoltz** [comment]
> site documentation
> REST API documentation 

Commit: https://github.com/opengeospatial/ets-wfs30/commit/6c2a00af1b94dcce274fd0cf1bc4d75c090c49df

**Comment by lgoltz** [comment]
> site documentation

* Transformed md to adoc: https://github.com/opengeospatial/ets-wfs30/commit/b7ee82275a7b9f6923d2e5a224afdd81bab1d402
* Updated site: https://github.com/opengeospatial/ets-wfs30/commit/b7d63255a60afd93739ecd8f03c69cb1a72f1f83
* Extracted the information about how to run the test suite to avoid redundant information (in README and site): https://github.com/opengeospatial/ets-wfs30/commit/1c11cfd6f9b3a9dbca6038ebd8cc25836b2ce4f7

**Comment by lgoltz** [comment]
> Test result (link to JavaDoc)

Tested with 0.2-SNAPSHOT (local docker environment). The link in the new HTML report is broken, the one in the old report is correct.

**Current link:** http://opengeospatial.github.io/ets-wfs30 0.2/apidocs/org/opengis/cite/wfs30/collections/GetFeaturesOperation#boundingBoxParameter
**Expected:** http://opengeospatial.github.io/ets-wfs30/apidocs/org/opengis/cite/wfs30/collections/GetFeaturesOperation#boundingBoxParameter

If  the version is set to a non SNAPSHOT version, the link is fine. This seems to be a issue with the new HTML report and SNAPSHOT version.
